Fix xrdp service compatibility with CentOS 6

diff --git a/instfiles/init.d/xrdp b/instfiles/init.d/xrdp
--- a/instfiles/init.d/xrdp
+++ b/instfiles/init.d/xrdp
@@ -31,22 +31,101 @@ test -x $DAEMON || exit 0
 
 . /lib/lsb/init-functions
 
+#
+# Attempts to execute the provided command. If the command fails, checks to see
+# if the command's functionality has been overridden.
+#
+command_proxy() {
+    "$@" 2>/dev/null || command_override "$@"
+}
+
+#
+# Selectively overrides the functionality of some commands/functions for
+# compatibility with legacy OSes. If the command has not been overridden, then
+# its arguments will be echoed to STDOUT.
+#
+command_override() {
+    case "$1" in
+        'log_end_msg')
+            # ignore this command
+            ;;
+        'log_daemon_msg')
+            echo -n "${@:2}... "
+            ;;
+        'pidofproc')
+            pgrep -f "${@: -1}"
+            ;;
+        *)
+            echo "${@:2}"
+            ;;
+    esac
+}
+
+#
+# Manages daemon startup
+#
+start_daemon() {
+    user="$1"
+    pidfile="$2"
+    daemon="${@:3}"
+
+    ssd_cmd="start-stop-daemon --start --quiet --oknodo"
+    unset nohup_cmd
+
+    if [ "${pidfile}" != "" ]; then
+        ssd_cmd+=" --pidfile ${pidfile}"
+    fi
+
+    if [ "${user}" != "" ]; then
+        ssd_cmd+=" --chuid ${user}:${user}"
+        nohup_cmd="su - ${user} -c \"nohup bash -c '${daemon}' </dev/null &>/dev/null\""
+    else
+        nohup_cmd="nohup bash -c '${daemon}' <dev/null &>/dev/null"
+    fi
+
+    # if start-stop-daemon is not available, use nohup instead
+    ${ssd_cmd} ${daemon} 2>/dev/null || ${nohup_cmd} <dev/null &>/dev/null
+}
+
+#
+# Manages daemon shutdown
+#
+stop_daemon() {
+    user="$1"
+    pidfile="$2"
+    daemon="${@:3}"
+
+    ssd_cmd="start-stop-daemon --stop --quiet --oknodo"
+    pkill_cmd="pkill -f"
+
+    if [ "${pidfile}" != "" ]; then
+        ssd_cmd+=" --pidfile ${pidfile}"
+    fi
+
+    if [ "${user}" != "" ]; then
+        ssd_cmd+=" --chuid ${user}:${user}"
+        pkill_cmd+=" -u ${user}"
+    fi
+
+    # if start-stop-daemon is not available, use pkill instead
+    ${ssd_cmd} ${daemon} 2>/dev/null || ${pkill_cmd} "${daemon}"
+}
+
 check_root()  {
     if [ "$(id -u)" != "0" ]; then
-        log_failure_msg "You must be root to start, stop or restart $NAME."
+        command_proxy log_failure_msg "You must be root to start, stop or restart $NAME."
         exit 4
     fi
 }
 
 force_stop() {
-
-DELAY=1
-PROCLIST="xrdp-sesman xrdp-sessvc xrdp-chansrv X11rdp Xvnc"
+    DELAY=1
+    PROCLIST="xrdp-sesman xrdp-sessvc xrdp-chansrv X11rdp Xvnc"
 
     for p in $PROCLIST; do
-      pgrep -x $p >/dev/null && pkill  -x $p
-      sleep $DELAY
-      pgrep -x $p >/dev/null && pkill -9 -x $p
+        pgrep -x $p >/dev/null && pkill  -x $p
+        sleep $DELAY
+        pgrep -x $p >/dev/null && pkill -9 -x $p
     done
     # let's not kill ourselves - the init script is called xrdp as well
     pgrep -fx $DAEMON  >/dev/null && pkill -fx $DAEMON
@@ -57,7 +136,7 @@ PROCLIST="xrdp-sesman xrdp-sessvc xrdp-chansrv X11rdp Xvnc"
 }
 
 if [ -r /etc/default/$NAME ]; then
-   . /etc/default/$NAME
+    . /etc/default/$NAME
 fi
 
 # Tasks that can only be run as root
@@ -70,36 +149,34 @@ if [ "$(id -u)" = "0" ]; then
 
     # Check for rsa key 
     if [ ! -f $RSAKEYS ] ; then
-        log_action_begin_msg "Generating xrdp RSA keys..."
+        command_proxy log_action_begin_msg "Generating xrdp RSA keys..."
         (umask 077 ; xrdp-keygen xrdp $RSAKEYS)
         chown $USERID:$USERID $RSAKEYS
         if [ ! -f $RSAKEYS ] ; then
-            log_action_end_msg 1 "could not create $RSAKEYS"
+            command_proxy log_action_end_msg 1 "could not create $RSAKEYS"
             exit 1
         fi
-        log_action_end_msg 0 "done"
+        command_proxy log_action_end_msg 0 "done"
     fi
 fi
 
 
 case "$1" in
-  start)
+    start)
         check_root
         exitval=0
-        log_daemon_msg "Starting $DESC " 
-        if pidofproc -p $PIDDIR/$NAME.pid $DAEMON > /dev/null; then
-            log_progress_msg "$NAME apparently already running"
-            log_end_msg 0
+        command_proxy log_daemon_msg "Starting $DESC "
+        if command_proxy pidofproc -p $PIDDIR/$NAME.pid $DAEMON > /dev/null; then
+            command_proxy log_progress_msg "$NAME apparently already running"
+            command_proxy log_end_msg 0
             exit 0
         fi
-        log_progress_msg $NAME
-        start-stop-daemon --start --quiet --oknodo  --pidfile $PIDDIR/$NAME.pid \
-	    --chuid $USERID:$USERID --exec $DAEMON >/dev/null
+        command_proxy log_progress_msg $NAME
+        start_daemon "${USERID}" "$PIDDIR/$NAME.pid" "$DAEMON" >/dev/null
         exitval=$?
-	if [ "$SESMAN_START" = "yes" ] ; then
-            log_progress_msg "sesman"
-            start-stop-daemon --start --quiet --oknodo --pidfile $PIDDIR/xrdp-sesman.pid \
-	       --exec $SDAEMON >/dev/null
+        if [ "$SESMAN_START" = "yes" ] ; then
+            command_proxy log_progress_msg "sesman"
+            start_daemon "" "$PIDDIR/xrdp-sesman.pid" "$SDAEMON" >/dev/null
             value=$?
             [ $value -gt 0 ] && exitval=$value
         fi
@@ -108,80 +185,78 @@ case "$1" in
         [ -e $PIDDIR/$NAME.pid ] && chmod 0644 $PIDDIR/$NAME.pid
         # Note: Unfortunately, xrdp currently takes too long to create
         # the pidffile unless properly patched
-        log_end_msg $exitval
-	;;
-  stop)
+        command_proxy log_end_msg $exitval
+        ;;
+    stop)
         check_root
-	[ -n "$XRDP_UPGRADE" -a "$RESTART_ON_UPGRADE" = "no" ] && {
-	    echo "Upgrade in progress, no restart of xrdp."
-	    exit 0
-	}
+        [ -n "$XRDP_UPGRADE" -a "$RESTART_ON_UPGRADE" = "no" ] && {
+            echo "Upgrade in progress, no restart of xrdp."
+            exit 0
+        }
         exitval=0
-        log_daemon_msg "Stopping RDP Session manager " 
-        log_progress_msg "sesman"
-        if pidofproc -p  $PIDDIR/xrdp-sesman.pid $SDAEMON  > /dev/null; then
-            start-stop-daemon --stop --quiet --oknodo --pidfile $PIDDIR/xrdp-sesman.pid \
-                --chuid $USERID:$USERID --exec $SDAEMON
+        command_proxy log_daemon_msg "Stopping RDP Session manager "
+        command_proxy log_progress_msg "sesman"
+        if command_proxy pidofproc -p $PIDDIR/xrdp-sesman.pid $SDAEMON > /dev/null; then
+            stop_daemon "${USERID}" "${PIDDIR}/xrdp-sesman.pid" "${SDAEMON}"
             exitval=$?
         else
-            log_progress_msg "apparently not running"
+            command_proxy log_progress_msg "apparently not running"
         fi
-        log_progress_msg $NAME
-        if pidofproc -p  $PIDDIR/$NAME.pid $DAEMON  > /dev/null; then
-            start-stop-daemon --stop --quiet --oknodo --pidfile $PIDDIR/$NAME.pid \
-	    --exec $DAEMON
+        command_proxy log_progress_msg $NAME
+        if command_proxy pidofproc -p $PIDDIR/$NAME.pid $DAEMON > /dev/null; then
+            stop_daemon "" "${PIDDIR}/${NAME}.pid" "${DAEMON}"
             value=$?
             [ $value -gt 0 ] && exitval=$value
         else
-            log_progress_msg "apparently not running"
+            command_proxy log_progress_msg "apparently not running"
         fi
-        log_end_msg $exitval
-	;;
-  force-stop)
-	$0 stop
-	# because it doesn't allways die the right way
-	force_stop
-	;;
-  restart|force-reload)
+        command_proxy log_end_msg $exitval
+        ;;
+    force-stop)
+        $0 stop
+        # because it doesn't allways die the right way
+        force_stop
+        ;;
+    restart|force-reload)
         check_root
-	$0 stop
+        $0 stop
         # Wait for things to settle down
         sleep 1
-	$0 start
-	;;
-  reload)
-        log_warning_msg "Reloading $NAME daemon: not implemented, as the daemon"
-        log_warning_msg "cannot re-read the config file (use restart)."
+        $0 start
         ;;
-  status)
+    reload)
+        command_proxy log_warning_msg "Reloading $NAME daemon: not implemented, as the daemon"
+        command_proxy log_warning_msg "cannot re-read the config file (use restart)."
+        ;;
+    status)
         exitval=0
-        log_daemon_msg "Checking status of $DESC" "$NAME"
-        if pidofproc -p  $PIDDIR/$NAME.pid $DAEMON  > /dev/null; then
-            log_progress_msg "running"
-            log_end_msg 0
+        command_proxy log_daemon_msg "Checking status of $DESC" "$NAME"
+        if command_proxy pidofproc -p $PIDDIR/$NAME.pid $DAEMON > /dev/null; then
+            command_proxy log_progress_msg "running"
+            command_proxy log_end_msg 0
         else
-            log_progress_msg "apparently not running"
-            log_end_msg 1 || true
+            command_proxy log_progress_msg "apparently not running"
+            command_proxy log_end_msg 1 || true
             exitval=1
         fi
-	if [ "$SESMAN_START" = "yes" ] ; then
-            log_daemon_msg "Checking status of RDP Session Manager" "sesman"
-            if pidofproc -p  $PIDDIR/xrdp-sesman.pid $SDAEMON  > /dev/null; then
-                log_progress_msg "running"
-                log_end_msg 0
+        if [ "$SESMAN_START" = "yes" ] ; then
+            command_proxy log_daemon_msg "Checking status of RDP Session Manager" "sesman"
+            if command_proxy pidofproc -p $PIDDIR/xrdp-sesman.pid $SDAEMON > /dev/null; then
+                command_proxy log_progress_msg "running"
+                command_proxy log_end_msg 0
             else
-                log_progress_msg "apparently not running"
-                log_end_msg 1 || true
+                command_proxy log_progress_msg "apparently not running"
+                command_proxy log_end_msg 1 || true
                 exitval=1
             fi
-	fi
+        fi
         exit $exitval
         ;;
-  *)
-	N=/etc/init.d/$NAME
-	echo "Usage: $N {start|stop|force-stop|restart|force-reload|status}" >&2
-	exit 1
-	;;
+    *)
+        N=/etc/init.d/$NAME
+        echo "Usage: $N {start|stop|force-stop|restart|force-reload|status}" >&2
+        exit 1
+        ;;
 esac
 
 exit 0
